server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&charterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ok

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
mybatis:
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.progect.sm.entity

logging:
  level:
    com:
      zb:
        progect:
          sm:
            dao: debug

